title: たぬきの部屋
description: 音ゲー(IIDX)や謎のアプリ開発にいそしむ男。ごくまれに楽器演奏(Gt/Key)。
markdown: kramdown
url: "https://dj-kata.github.io"
image: /assets/icons/tanuki_face.png

# for atom feed
author:
  name: kaze / Jun Kawahara
  email: kawahara3.exe@gmail.com

plugins:
  - jemoji
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-feed

collections_dir: all_collections
collections:
  posts:
    output: true

defaults:
  - scope:
      path: "_posts"
    values:
      layout: "post"
      permalink: /posts/:title/
exclude: ["sitemap.xml", "feed.xml", "LICENSE", "README.md"]
